name: Build Project

on: [push]
jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Build
        run: sudo make
            
