name: Build Project

on: [push]
jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Setup chroot
        run: |
          su root
          chroot $(pwd) /busybox ash
      - name: Build TCC
        run: /busybox ash initboot.sh
            
